export const APP = {
  SET_LOADING: 'APP/SET_LOADING',
};

export const USER = {
  SET_AUTH_STATE: 'USER/SET_AUTH_STATE',
  SET_ACCESS_TOKEN: 'USER/SET_ACCESS_TOKEN',
  SET_CURRENT_USER: 'USER/SET_CURRENT_USER',
  SET_PROFILE_TYPE: 'USER/SET_PROFILE_TYPE',
  SET_IS_AUTHENTICATING: 'USER/SET_IS_AUTHENTICATING',
  LOGOUT_SUCCESS: 'USER/LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'USER/LOGOUT_FAILURE'
};

export const ACCOUNTS = {
  FETCHING_ACCOUNTS_SCREEN: 'ACCOUNTS/FETCHING_ACCOUNTS_SCREEN',
  FETCH_ACCOUNTS_SCREEN_SUCCESS: 'ACCOUNTS/FETCH_ACCOUNTS_SCREEN/SUCCESS',
  FETCH_ACCOUNTS_SCREEN_FAILURE: 'ACCOUNTS/FETCH_ACCOUNTS_SCREEN/FAILURE',
  FETCHING_ACCOUNT_DETAILS: 'ACCOUNTS/FETCHING_ACCOUNT_DETAILS',
  FETCH_ACCOUNT_DETAILS_SUCCESS: 'ACCOUNTS/FETCH_ACCOUNT_DETAILS_SUCCESS',
  FETCH_ACCOUNT_DETAILS_FAILURE: 'ACCOUNTS/FETCH_ACCOUNT_DETAILS_FAILURE',
  SET_CURRENT_ACCOUNT: 'ACCOUNTS/SET_CURRENT_ACCOUNT',
  SET_FILTERING: 'ACCOUNTS/SET_FILTERING',
  SET_FILTERED_RECORDS: 'ACCOUNTS/SET_FILTERED_RECORDS'
};

export const CASES = {
  FETCHING_CASES: 'CASES/FETCHING_CASES',
  FETCH_CASES_SUCCESS: 'CASES/FETCH_CASES/SUCCESS',
  FETCH_CASES_FAILURE: 'CASES/FETCH_CASES/FAILURE'
};

export const CONTACTS = {
  FETCHING_CONTACTS: 'CONTACTS/FETCHING_CONTACTS',
  FETCH_CONTACTS_SUCCESS: 'CONTACTS/FETCH_CONTACTS/SUCCESS',
  FETCH_CONTACTS_FAILURE: 'CONTACTS/FETCH_CONTACTS/FAILURE'
};

export const PRODUCTS = {
  FETCHING_PRODUCTS_SCREEN: 'PRODUCTS/FETCHING_PRODUCTS_SCREEN',
  FETCH_PRODUCTS_SCREEN_SUCCESS: 'PRODUCTS/FETCH_PRODUCTS_SCREEN/SUCCESS',
  FETCH_PRODUCTS_SCREEN_FAILURE: 'PRODUCTS/FETCH_PRODUCTS_SCREEN/FAILURE',
  FETCHING_PRODUCT_DETAILS: 'PRODUCTS/FETCHING_PRODUCT_DETAILS',
  FETCH_PRODUCT_DETAILS_SUCCESS: 'PRODUCTS/FETCH_PRODUCT_DETAILS_SUCCESS',
  FETCH_PRODUCT_DETAILS_FAILURE: 'PRODUCTS/FETCH_PRODUCT_DETAILS_FAILURE',
  SET_CURRENT_PRODUCT: 'PRODUCTS/SET_CURRENT_PRODUCT',
};
