export const APP = {
  SET_LOADING: 'APP/SET_LOADING',
};

export const USER = {
  SET_AUTH_STATE: 'USER/SET_AUTH_STATE',
  SET_ACCESS_TOKEN: 'USER/SET_ACCESS_TOKEN',
  SET_CURRENT_USER: 'USER/SET_CURRENT_USER',
  SET_PROFILE_TYPE: 'USER/SET_PROFILE_TYPE',
  SET_IS_AUTHENTICATING: 'USER/SET_IS_AUTHENTICATING'
};

export const ACCOUNTS = {
  FETCHING_ACCOUNTS: 'ACCOUNTS/FETCHING_ACCOUNTS',
  FETCH_ACCOUNTS_SUCCESS: 'ACCOUNTS/FETCH_ACCOUNTS/SUCCESS',
  FETCH_ACCOUNTS_FAILURE: 'ACCOUNTS/FETCH_ACCOUNTS/FAILURE'
};

export const CASES = {
  FETCHING_CASES: 'CASES/FETCHING_CASES',
  FETCH_CASES_SUCCESS: 'CASES/FETCH_CASES/SUCCESS',
  FETCH_CASES_FAILURE: 'CASES/FETCH_CASES/FAILURE'
};

export const CONTACTS = {
  FETCHING_CONTACTS: 'CONTACTS/FETCHING_CONTACTS',
  FETCH_CONTACTS_SUCCESS: 'CONTACTS/FETCH_CONTACTS/SUCCESS',
  FETCH_CONTACTS_FAILURE: 'CONTACTS/FETCH_CONTACTS/FAILURE'
};

export const PRODUCTS = {
  FETCHING_PRODUCTS: 'PRODUCTS/FETCHING_PRODUCTS',
  FETCH_PRODUCTS_SUCCESS: 'PRODUCTS/FETCH_PRODUCTS/SUCCESS',
  FETCH_PRODUCTS_FAILURE: 'PRODUCTS/FETCH_PRODUCTS/FAILURE'
};
